# Generated by Django 5.0.6 on 2024-08-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.FloatField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="book",
            name="price",
        ),
        migrations.AddField(
            model_name="book",
            name="price",
            field=models.ManyToManyField(
                blank=True, related_name="prices", to="base.price"
            ),
        ),
    ]
