# Generated by Django 5.0.6 on 2024-08-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_price_remove_book_price_book_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="price",
            field=models.ManyToManyField(
                blank=True, related_name="books", to="base.price"
            ),
        ),
    ]
