# Generated by Django 5.0.6 on 2024-08-10 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_alter_book_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="price",
        ),
        migrations.AddField(
            model_name="book",
            name="price",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="books",
                to="base.price",
            ),
        ),
    ]
