# Generated by Django 5.0.6 on 2024-08-10 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0006_categories_book_categories"),
    ]

    operations = [
        migrations.CreateModel(
            name="Age",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age_range", models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name="book",
            old_name="Categories",
            new_name="categories",
        ),
        migrations.AddField(
            model_name="book",
            name="age_range",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="books",
                to="base.age",
            ),
        ),
    ]
